css/admin.css, js/admin.js, templates/admin.php
Before:
After:
Optional settings could be expanded by clicking on the text:
cc @nextcloud/designers @LukasReschke
=> Replace tab based design with a scrollable design

appinfo/app.php, appinfo/database.xml, appinfo/info.xml, lib/appinfo/application.php, lib/controller/samlcontroller.php, lib/userbackend.php
So search etc. works fine
@MorrisJobke
=> Add SAML users to DB

lib/userbackend.php
That happens when testing locally with SQLite...
=> It should be uid not token

appinfo/info.xml
cc @LukasReschke @rullzer
for nextcloud/server#735
=> fix casing of user_saml app

appinfo/info.xml
cc @LukasReschke @rullzer
for nextcloud/server#735
Backport of #27
=> [stable10] fix casing of user_saml app

appinfo/app.php, appinfo/info.xml, lib/Settings/Admin.php, lib/Settings/Section.php, lib/controller/settingscontroller.php
Makes this page a single page as implemented in https://github.com/nextcloud/server/pull/796
=> Use new admin page module

appinfo/app.php, appinfo/info.xml, lib/Settings/Admin.php, lib/Settings/Section.php, lib/controller/settingscontroller.php
Use new admin page module
Makes this page a single page as implemented in https://github.com/nextcloud/server/pull/796
specify namespace for autoloader
IAdmin is now ISettings
@LukasReschke
=> Backport of #29 to stable10

lib/Settings/Admin.php, tests/Settings/AdminTest.php
=> Add tests for "Admin"

appinfo/app.php, lib/userbackend.php, tests/UserBackendTest.php
Ref nextcloud/server#2599
@LukasReschke @blizzz
=> Do not use deprecated class anymore

lib/samlsettings.php
=> [stable11] Enable strict mode

lib/samlsettings.php
=> [stable10] Enable strict mode

lib/samlsettings.php
=> [stable9] Enable strict mode

.drone.yml, appinfo/app.php, lib/Controller/SAMLController.php, tests/integration/features/EnvironmentVariable.feature, tests/integration/features/bootstrap/FeatureContext.php, tests/integration/vendor/composer/ClassLoader.php, tests/integration/vendor/composer/installed.json
This adds integration tests for the environment variable authentication method and also fixes an issue with the Environment Variable auth where the account was setup too early and thus the account couldn't login effectively. (as the SAML app believed the user was already logged-in)
The integration tests should cover these stuff for the future.
=> Add integration test for Environment Variable

appinfo/info.xml, templates/admin.php
Requires https://github.com/nextcloud/documentation/pull/346
=> Add link to admin documentation

lib/Controller/SAMLController.php
=> Log last error reason

.drone.yml
=> Update stable12 target versions

.drone.yml, appinfo/info.xml
=> Make compatible with Nextcloud 13

lib/userbackend.php
To get in sync with https://github.com/nextcloud/server/pull/5864
=> Use proper namespace for user backend

tests/integration/features/Shibboleth.feature, tests/integration/features/bootstrap/FeatureContext.php
=> Add test for keeping display name after login

tests/integration/features/Shibboleth.feature, tests/integration/features/bootstrap/FeatureContext.php
Reverts nextcloud/user_saml#135
=> Revert "Add test for keeping display name after login"

appinfo/app.php, lib/AppInfo/Application.php, lib/SAMLSettings.php
=> baseurl is expected to be the host name and protocol without path

.drone.yml, lib/Controller/SAMLController.php, lib/UserBackend.php, tests/integration/features/EnvironmentVariable.feature, tests/integration/features/Shibboleth.feature, tests/integration/features/bootstrap/FeatureContext.php, tests/unit/Controller/SAMLControllerTest.php, tests/unit/UserBackendTest.php
1. Includes remaining patch from https://github.com/nextcloud/user_saml/pull/132
2. Fixes https://github.com/nextcloud/user_saml/issues/103
=> Set last login after successful login operation

lib/UserBackend.php
For https://github.com/nextcloud/server/pull/6177
Fixes https://github.com/nextcloud/user_saml/issues/112
=> Implement new SLO URL API

appinfo/info.xml, js/admin.js, templates/admin.php
Older releases have an incompatible change in the IApache backend.
=> Require 12.0.3 as minimum version

CHANGELOG.md, appinfo/info.xml
=> Bump version to 1.4.0

.drone.yml, appinfo/info.xml, lib/UserBackend.php
=> Run tests against older stable12 releases

lib/UserBackend.php
update the display name in accounts table
fix https://github.com/nextcloud/user_saml/issues/144
=> update the display name in accounts table

lib/Settings/Admin.php, lib/UserBackend.php, tests/unit/Settings/AdminTest.php, tests/unit/UserBackendTest.php
Allows to specify a customer mapping for the quota element.
I need to think about the best way to test this.
=> Add support for mapping the quota

lib/Settings/Admin.php, lib/UserBackend.php, tests/unit/Settings/AdminTest.php, tests/unit/UserBackendTest.php
=> [stable13] Support quota

appinfo/app.php, appinfo/routes.php, css/admin.css, css/selectUserBackEnd.css, lib/Controller/SAMLController.php, lib/Settings/Admin.php, templates/selectUserBackEnd.php, tests/unit/AppInfo/RoutesTest.php, tests/unit/Controller/SAMLControllerTest.php, tests/unit/Settings/AdminTest.php
backport of https://github.com/nextcloud/user_saml/pull/196
cc @blizzz @MorrisJobke @rullzer
=> Multiple user back ends stable13

lib/Controller/SAMLController.php, tests/unit/Controller/SAMLControllerTest.php
=> [stable11] try to lookup a user if the uid does not resolve and autoprov is disables

lib/Controller/SAMLController.php, tests/unit/Controller/SAMLControllerTest.php
=> [stable12] try to lookup a user if the uid does not resolve and autoprov is disabled

templates/admin.php
=> update warning to match the new option to have multiple user back-ends enabled in parallel

3rdparty/composer.json, 3rdparty/vendor/composer/ClassLoader.php, 3rdparty/vendor/composer/LICENSE, 3rdparty/vendor/composer/autoload_real.php
So we don't try to load other classes with this autoloader.
=> Use authoriative autoloader

templates/admin.php
backport of https://github.com/nextcloud/user_saml/pull/200
=> [stable13] update warning to match the new option to have multiple user back-ends enabled in parallel

appinfo/app.php, lib/Settings/Admin.php, lib/UserBackend.php, tests/unit/Settings/AdminTest.php, tests/unit/UserBackendTest.php
Improved PR #95:
- Also removes groups based on the group attribute(s).
- Supports groups with spaces (which the previous PR didn't).
- Includes unit test
=> Group mapping

appinfo/app.php, lib/Settings/Admin.php, lib/UserBackend.php, tests/unit/Settings/AdminTest.php, tests/unit/UserBackendTest.php
Backport of #185 to the stable13 branch.
=> Group mapping (stable13)

lib/UserBackend.php
Code taken from 'regular' login method do create skeleton and dispatch event of the user creation.
A better idea would be to directly use the `prepareUserLogin()` method of `lib/private/User/Session.php`, but as it is private...
This should fix https://github.com/nextcloud/user_saml/issues/172
=> Create skeleton and dispatch first login event for auto-created accounts

lib/Controller/SAMLController.php
This makes sure the auth flow also works with the direct login.
=> Follow the redirect url on direct login

lib/Controller/SAMLController.php
=> [stable13] Follow the redirect url on direct login

CHANGELOG.md, Makefile
Signed-off-by: Bjoern Schiessle <bjoern@schiessle.org>
=> prepare v1.6.0

lib/Controller/SAMLController.php
rebased from here: https://github.com/nextcloud/user_saml/pull/240
=> Add orignalURL to redirect when using SSO

3rdparty/composer.json, 3rdparty/composer.lock, 3rdparty/vendor/composer/ClassLoader.php, 3rdparty/vendor/composer/LICENSE, 3rdparty/vendor/composer/autoload_classmap.php, 3rdparty/vendor/composer/autoload_psr4.php, 3rdparty/vendor/composer/autoload_static.php, 3rdparty/vendor/composer/installed.json, 3rdparty/vendor/firebase/php-jwt/LICENSE, 3rdparty/vendor/firebase/php-jwt/README.md, 3rdparty/vendor/firebase/php-jwt/composer.json, 3rdparty/vendor/firebase/php-jwt/composer.lock, 3rdparty/vendor/firebase/php-jwt/package.xml, 3rdparty/vendor/firebase/php-jwt/src/BeforeValidException.php, 3rdparty/vendor/firebase/php-jwt/src/ExpiredException.php, 3rdparty/vendor/firebase/php-jwt/src/JWT.php, 3rdparty/vendor/firebase/php-jwt/src/SignatureInvalidException.php, appinfo/app.php, appinfo/info.xml, lib/Controller/SAMLController.php, lib/UserBackend.php, tests/unit/Controller/SAMLControllerTest.php, tests/unit/UserBackendTest.php
don't auto provision users on the Global Site Selector in a Global Scale setup
=> make SAML app ready for Global Scale

lib/UserBackend.php
an easy one... @nickvergessen do you remember? :wink:
=> add missing use clause

css/selectUserBackEnd.css
fix https://github.com/nextcloud/user_saml/issues/259
thanks @skjnldsv
=> adjust button background to theme color

lib/Controller/SAMLController.php
Signed-off-by: Robin Appelman <robin@icewind.nl>
=> log provisioning errors during sso environment login

.drone.yml, tests/unit/bootstrap.php
let's try to add php 7.3 (and php 7.2) tests
=> add php 7.3 tests

js/selectUserBackEnd.js, templates/selectUserBackEnd.php
fix select idp combobox so that it also works with chromium
=> fix select idp combobox so that it also works with chromium

appinfo/app.php, lib/AppInfo/Application.php, lib/DavPlugin.php, tests/unit/Controller/SAMLControllerTest.php
For https://github.com/nextcloud/user_saml/issues/181
Makes environment variable sso (i.e. kerberos) work with webdav requests
=> Add sabredav plugin to register environment auth for dav requests

lib/SAMLSettings.php
sort IDP's alphabetically to make it easier for the user to find the right one
=> sort idps alphabetically

lib/Controller/SAMLController.php
Reported at Transifex.
Signed-off-by: Mark Ziegler <mark.ziegler@rakekniven.de>
=> Fixed typo.

.drone.yml, tests/integration/features/bootstrap/FeatureContext.php
=> adjust config to drone  1.0

lib/UserBackend.php
add additional debug output when reading attributes from the IDP
=> add additional debug output when reading attributes from the IDP

lib/UserBackend.php
Only the uid was searched before (when using getUsers which is usually used for searches).
=> user search parity as with local users

appinfo/app.php
Fixes #283 
This avoids diabling the user_saml app on random PUT requests to the Nextcloud instance without a proper Content-Type.
=> Catch exception during parameter fetching

appinfo/routes.php, js/timezone.js, lib/AppInfo/Application.php, lib/Controller/TimezoneController.php, tests/unit/AppInfo/RoutesTest.php
=> Load a timezone file if no timezone is set

3rdparty/vendor/composer/installed.json, 3rdparty/vendor/onelogin/php-saml/CHANGELOG, 3rdparty/vendor/onelogin/php-saml/README.md, 3rdparty/vendor/onelogin/php-saml/composer.json, 3rdparty/vendor/onelogin/php-saml/settings_example.php, 3rdparty/vendor/onelogin/php-saml/src/Saml2/Auth.php, 3rdparty/vendor/onelogin/php-saml/src/Saml2/LogoutRequest.php, 3rdparty/vendor/onelogin/php-saml/src/Saml2/Response.php, 3rdparty/vendor/onelogin/php-saml/src/Saml2/Utils.php, 3rdparty/vendor/onelogin/php-saml/src/Saml2/version.json
=> Bump php-saml to 3.1.1

.drone.yml
=> Add tests against 16

.drone.yml
Branch won't exist if this is coming from a fork
This should fix it
=> Fix testing on forks

.drone.yml
=> Add testing for stable17

appinfo/info.xml, templates/admin.php
fixes #244 
continues https://github.com/nextcloud/user_saml/pull/315
Signed-off-by: Sascha Wiswedel <sascha.wiswedel@nextcloud.com>
=> added link to portal documentation

.drone.yml, lib/UserBackend.php
This will allow reporting to also list the number of SAML users on the
instance.
=> Add counting to the user backend

.drone.yml, appinfo/info.xml, tests/unit/AppInfo/ApplicationTest.php, tests/unit/Controller/SAMLControllerTest.php, tests/unit/Middleware/OnlyLoggedInMiddlewareTest.php, tests/unit/Settings/AdminTest.php, tests/unit/Settings/SectionTest.php, tests/unit/UserBackendTest.php
=> Update master php testing versions

appinfo/info.xml
=> Make 19 compatible

lib/Controller/SAMLController.php
=> fixed login with chrome browser

.drone.yml, appinfo/info.xml
=> bump version for 2.4.1

lib/UserBackend.php
=> [stable-2.4] Add counting to the user backend

lib/Controller/SAMLController.php, lib/UserBackend.php, tests/unit/Controller/SAMLControllerTest.php, tests/unit/UserBackendTest.php
=> [stable-2.4] Handle ObjectGUID claims

.drone.yml
=> use new image for CI that should ensure that LDAP is available

.drone.yml, appinfo/info.xml
2.4 edition of #394 plus phasing out 15
=> [stable2.4] use new image for CI that should ensure that LDAP is available 

appinfo/app.php
Signed-off-by: Julius Härtl <jus@bitgrid.net>
=> Setup Application class using query()

.drone.yml
=> Update master target versions

appinfo/app.php
=> Ignore the oauth token path in login with the environment variables

.drone.yml, appinfo/info.xml
there is another PR ready to be merged addressing 19 specifically. And 20 will have it's own, too.
=> >=3.1.3 to become compatible with 18 only

lib/DavPlugin.php
Required once https://github.com/nextcloud/server/pull/19325 is in
=> Sabre/DAV 4.0: beforeMethod is now beforeMethod:*

.drone.yml, appinfo/info.xml, tests/integration/features/EnvironmentVariable.feature, tests/integration/features/Shibboleth.feature
left out the bootstrap part yet. not for tonight.
=> Bump version, require 20, adjust integration tests

.drone.yml, appinfo/info.xml
=> 3.2 series is now 19 only

lib/Controller/SAMLController.php
* the void statements end up in a useless blank page
like https://github.com/nextcloud/user_saml/pull/414, but catches more cases and requires a RedirectResponse  for the method.
=> acs endpoint to always return a RedirectResponse

lib/Controller/SAMLController.php
Stable19 did not yet have all the constants
=> use the correct session names

lib/Controller/SettingsController.php, lib/SAMLSettings.php, templates/admin.php
=> optional possibility to provide a URL for SLO Response

lib/Controller/SAMLController.php
Might help to get a hint on why a configuration is not working properly
=> Add checked user id to InvalidArgumentException

.drone.yml
=> Bump php version for Nextcloud 21

CHANGELOG.md, appinfo/info.xml, lib/Migration/Version3001Date20200630193443.php
=> Bump doctrine types for 21 support

lib/Controller/SAMLController.php
To make debugging SLO errors easier, this adds logging for any
encountered error in that phase.
This is similar to the logging already done on the ACS handling.
=> Add logging for SLO errors

.github/workflows/composer.yml
otherwise we see it only on packaging
=> check that all depenencies are installed

appinfo/app.php, lib/Controller/SAMLController.php, lib/UserBackend.php, lib/UserData.php, lib/UserResolver.php, tests/unit/AppInfo/RoutesTest.php, tests/unit/Controller/SAMLControllerTest.php, tests/unit/UserBackendTest.php, tests/unit/UserDataTest.php
=> sanitize and test user id received from IdP, if original does not match

.drone.yml, appinfo/info.xml, tests/unit/Controller/SAMLControllerTest.php, tests/unit/Middleware/OnlyLoggedInMiddlewareTest.php
=> Update version on master

.drone.yml
Avoid having two different runs
=> Apply triggers on all tests

appinfo/app.php
Signed-off-by: Carl Schwan <carl@carlschwan.eu>
=> Handle mobile login flow with direct=1

.github/workflows/lint-info-xml.yml
Automated update of the lint-info-xml.yml workflow from https://github.com/nextcloud/.github
=> Updating lint-info-xml.yml workflow from template

lib/Settings/Admin.php, tests/unit/Settings/AdminTest.php
Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>
=> l10n: Change place of dot

lib/Controller/SAMLController.php
The relay state does currently not respect any overwrite parameters that are set in the Nextcloud config
Fixes #523
=> Set proper relaystate url

CHANGELOG.md
No code changes, just the changelog was updated.
=> add changelog for 4.1.1, update for 5.0.0

appinfo/app.php
This reverts commit 86684d6c5473765b9fc3c7f3146f214cbce0dfd4.
=> Revert "Handle mobile login flow with direct=1"

appinfo/routes.php, css/admin.css, js/admin.js, lib/Controller/SAMLController.php, lib/Exceptions/UserFilterViolationException.php, lib/SAMLSettings.php, lib/Settings/Admin.php, lib/UserData.php, templates/admin.php, templates/notPermitted.php, tests/unit/Controller/SAMLControllerTest.php, tests/unit/Settings/AdminTest.php
- allow to specify groups for rejection
- allow to specify groups required to auth
=> add user filtering caps by group memberships

.github/workflows/phpunit-mysql.yml, .github/workflows/phpunit-oci.yml, .github/workflows/phpunit-pgsql.yml
Signed-off-by: John Molakvoæ <skjnldsv@users.noreply.github.com>
=> Add more phpunit testing

lib/Controller/SAMLController.php
When the session, and thus the stored IdP ID, is not present, walk the available configurations, until one is found that does not result in errors. So far I did not take the permanent cookie route, as we cannot rely on it either and would need a fallback. It would be a good addition still. 
This might take a little when there are hundreds of SAML configurations though. Might need to have a better solution for those cases.
=> gently handle incoming SAML Logout Request when the session is missing

lib/Settings/Admin.php
Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>
=> l10n: Change to uppercase

.drone.yml
=> chore(CI): Adjust testing matrix for Nextcloud 26 on master

.drone.yml, .github/workflows/phpunit-sqlite.yml
=> chore(CI): Adjust testing matrix for Nextcloud 27 on master

lib/Controller/SAMLController.php
Because of the new behavior of clear() it seems necessary to extract the idp from the jwt string generated by globalsiteselector.
=> extract idp from jwt in globalscale

css/admin.css
=> Better distinguish admin sections

lib/SAMLSettings.php
Fix https://github.com/nextcloud/user_saml/issues/694
=> Ensure $configurations is an array

.github/workflows/appstore-build-publish.yml, .github/workflows/lint-info-xml.yml, .github/workflows/lint-php-cs.yml, .github/workflows/lint-php.yml, .github/workflows/phpunit-mysql.yml, .github/workflows/phpunit-oci.yml, .github/workflows/phpunit-pgsql.yml, .github/workflows/phpunit-sqlite.yml, lib/Command/GetMetadata.php, lib/Controller/SAMLController.php, lib/Helper/TXmlHelper.php
=> [stable-5.1] fix(saml): enable xml entity loader where necessary

.drone.yml, .github/workflows/phpunit-mysql.yml, .github/workflows/phpunit-oci.yml, .github/workflows/phpunit-pgsql.yml, .github/workflows/phpunit-sqlite.yml
=> [stable-5.2] ci(tests): do not run against NC master anymore

lib/UserBackend.php
=> fix: Implement IGetDisplayNameBackend

CHANGELOG.md, appinfo/info.xml
Signed-off-by: Julius Härtl <jus@bitgrid.net>
=> chore(release): Bump version to 5.2.3

appinfo/app.php, lib/Controller/SAMLController.php, lib/UserBackend.php, tests/unit/Controller/SAMLControllerTest.php, tests/unit/UserBackendTest.php
- replace ::firtLogin with UserFirstTimeLoggedInEvent
- replace ILogger with PSR's LoggerInterface
=> fix(backend): remove deprecated event and class

CHANGELOG.md, appinfo/app.php, lib/Controller/SAMLController.php, lib/Controller/SettingsController.php, lib/Controller/TimezoneController.php, lib/Middleware/OnlyLoggedInMiddleware.php, lib/SAMLSettings.php, lib/Settings/Admin.php, lib/UserBackend.php, lib/UserData.php, tests/psalm-baseline.xml
- remove dead code and unused variables
- resolve deprecations
- remove unneeded and/or outdated php doc
- add type hints
=> chore(cleanup): prepare for 28 availability

lib/Controller/SAMLController.php, tests/unit/Controller/SAMLControllerTest.php
=> [stable-5.2] refactor(Controller): read parameter only once

lib/Controller/SAMLController.php
[Same logic as the regular SAML login](https://github.com/nextcloud/user_saml/blob/8a6a667e1496ec55dbfb92bb86817b7f2f396909/lib/Controller/SAMLController.php#L409) which should also apply when using environment based authentication
=> fix: Also create skeleton for users from environment based auth

appinfo/info.xml
There was over 40 downloads of the RC1, but since then no bugs reported here or in the forums.
=> meta(release): 6.1.0

lib/AppInfo/Application.php, tests/integration/features/bootstrap/FeatureContext.php
- the old style event name does not work here anymore
=> fix(User): load timezone handling related resources

lib/UserBackend.php
fixes #826
Addendum to e8a60d566d2eba6cf13bc80e2f8811ecaad7f145, it should have been removed with that commit already.
=> fix(Login): do not advertise CHECK_PASSWORD capability

.github/workflows/integration.yml
=> chore(CI): Adjust testing matrix for Nextcloud 30 on master

.github/workflows/integration.yml
=> chore(CI): Adjust testing matrix for Nextcloud 31 on master

lib/Settings/Admin.php, tests/unit/Settings/AdminTest.php
=> chore(i18n): Changed spelling of entity ID

lib/UserResolver.php
re-align with LDAP's sanitizerUsername()
fixes #572
=> fix(Resolver): replace iconv

.github/workflows/integration.yml
=> chore(CI): Adjust testing matrix for Nextcloud 32 on master
