js/admin.js, templates/admin.php
For: https://github.com/nextcloud/server/issues/735
* Save next to title
* Slide extra options in/out
CC: @jancborchardt @LukasReschke @schiessle @icewind1991 @blizzz @MorrisJobke
=> Release Polish

.drone.yml, js/admin.js
Previously the JS reloaded the page or gave the user no indication that a password confirmation was required. Thus not saving the changes.
Will prepare a port to stable11 as well once that gots reviewed.
=> Make the JS work with sudo mode

appinfo/info.xml
The SAML library that we use requires mcrypt at the moment.
Fixes https://github.com/nextcloud/user_saml/issues/55
=> Require mcrypt

lib/Controller/SAMLController.php, lib/Settings/Section.php, lib/samlsettings.php, tests/unit/Controller/SAMLControllerTest.php, tests/unit/Settings/SectionTest.php
1. Enable `debug` mode if debug mode is enabled in config.php
2. Log errors to the log file
Also I fixed the unit tests that broke with https://github.com/nextcloud/user_saml/pull/81
=> Add better error handling

lib/samlsettings.php
In case the protected server is behind reverse proxies with a different protocol this is required.
Fixes https://github.com/nextcloud/user_saml/issues/120
=> Add baseurl to SAML settings

lib/Controller/SAMLController.php
Some IDPs redirect to the SLS page after pressing the logout link. While this is a questionable behaviour it is unlikely we can change that, so let's work around this by forcing a proper redirect.
=> Redirect to `/` if CSRF check does not pass

lib/Controller/SAMLController.php
This is in master (13) now with https://github.com/nextcloud/server/pull/6630
Stable12 will just ignore this.
=> Use @NoSameSiteCookieRequired annotation

lib/Controller/SAMLController.php
In some wired setup and with some attributes it might happen that the IdP doesn't send a valid uid to the Nextcloud server
=> add a meaningful error message in case a empty uid is given

.drone.yml, appinfo/app.php, appinfo/routes.php, lib/Controller/SAMLController.php, tests/unit/AppInfo/RoutesTest.php, tests/unit/Controller/SAMLControllerTest.php
backport of https://github.com/nextcloud/user_saml/pull/190
detect disabled user and show a appropriated error message
Steps to test:
1. setup Nextcloud with SAML
2. Disable a saml user in the user management
3. Try to login with the disabled user
Until now: it result in a redirect loop between Nextcloud and the idp
With this PR: a appropriated error message is shown.
=> Detect disabled user stable13

lib/Controller/SAMLController.php, tests/unit/Controller/SAMLControllerTest.php
candidate to fix #162
it requires that a user can be found when a search is done against the "uid" that was returned from SAML.
Alternative would be to specify and request an attribute that should be used to discover the user. 
What do you think @schiessle?
=> try to lookup a user if the uid does not resolve and autoprov is disabled

appinfo/app.php, appinfo/routes.php, css/admin.css, css/selectUserBackEnd.css, lib/Controller/SAMLController.php, lib/Settings/Admin.php, templates/selectUserBackEnd.php, tests/unit/AppInfo/RoutesTest.php, tests/unit/Controller/SAMLControllerTest.php, tests/unit/Settings/AdminTest.php
add option to enable multiple user back-ends in parallel (see second check box from the saml admin settings) and to give the identity provider a custom display name (see first input field):
The user will then see this landing page and can decide between SSO and "direct login" which can be any user management which authenticates directly at Nextcloud (local user management, ldap,...). The SSO button has either the default name, as show here or the display name configured above.
@rullzer maybe you can give it a try and review it? Thanks!
=> Multiple user back ends

appinfo/app.php, appinfo/routes.php, css/admin.css, js/admin.js, lib/Controller/SAMLController.php, lib/Controller/SettingsController.php, lib/SAMLSettings.php, lib/Settings/Admin.php, lib/UserBackend.php, templates/admin.php, templates/selectUserBackEnd.php, tests/integration/features/bootstrap/FeatureContext.php, tests/unit/AppInfo/RoutesTest.php, tests/unit/Controller/SAMLControllerTest.php, tests/unit/Settings/AdminTest.php, tests/unit/UserBackendTest.php
As discussed with @schiessle this is the frontend part for adding multiple SAML providers. 
The config parameters are stored as before for the first provider and prefixed with `ID-` for the others. The list of ids that are configured is available in the app config value of `providerIds`, separated by `,`.
I would guess the following options are only one-time and not per provider:
- Only allow authentication if an account exists on some other backend. (e.g. LDAP)
- Allow the use of multiple user back-ends (e.g. LDAP)
- Use SAML auth for the Nextcloud desktop clients (requires user re-authentication)
Are there any other settings that should be global?
ToDo:
=> Allow to configure multiple providers

lib/Controller/SAMLController.php, lib/Settings/Admin.php, templates/admin.php, tests/unit/Settings/AdminTest.php
@juliushaertl found a small bug in the new saml settings. Multiple user back-ends are not supported when environment variables are used for authenticated. Can you have a look at my changes? Thanks!
cc @rullzer for the second review
=> we only allow multiple user back ends in combination with SAML, not with environment variables

appinfo/app.php, css/admin.css, js/admin.js, templates/admin.php
add a button to reset the config and go back to the initial setup to start over.
To lower the risk that the user will lose the configuration by accident we only remove the "saml type", this is enough to show again the default login screen and let you start the configuration from scratch. But you will stiff have the previous configuration if you chose one of the SSO type
=> Add reset option

lib/SAMLSettings.php
make sure that we don't show the "select user back-end login screen if authentication over environment variables has been chosen
=> make sure that we don't show the "select user back-end login screen if authentication over environment variables has been chosen

appinfo/info.xml, lib/Controller/SAMLController.php, tests/unit/Controller/SAMLControllerTest.php
- we need to store at least some basic user information to perform operations like "userExists()" during login.
- mcryt dependency was removed a little bit to early
=> make saml work smoothly with Global Scale

appinfo/app.php
If the audit-log app is enabled and log level is set to "1". We have multiple failed login attempts in the audit.log during every page reload if the user is logged in via saml. This happens because we always load the app and call `handleApacheAuth()` while this should be only needed for login via environment variables.
With this fix we reduce this "login attempt" messages to one per page reload. The remaining one comes from here https://github.com/nextcloud/server/blob/master/apps/dav/lib/Connector/Sabre/Auth.php#L231. 
````
{"reqId":"vxjRSaLGZJZoU8zcS0tn","level":1,"time":"2018-10-29T22:10:20+00:00","remoteAddr":"127.0.0.1","user":"Schiessle","app":"admin_audit","method":"PROPFIND","url":"\/server\/remote.php\/dav\/files\/Schiessle\/","message":"Login attempt: …
```
=> only call handleApacheAuth() if we login via environment variables

lib/Controller/SAMLController.php, tests/unit/Controller/SAMLControllerTest.php
If this server acts as a global scale master and the user is not
a local admin of the server we just create the user and continue
no need to update additional attributes.
But for local users, e.g. the admins of the global scale master
we should complete the user setup with all attributes.
=> make global scale setup more robust

js/selectUserBackEnd.js, lib/Controller/SAMLController.php, templates/selectUserBackEnd.php
If you have multipe IDPs the login page looks like this:
This looks nice and is intuitive to use but it doesn't scale for a large number of IDPs, so I made this changes to switch to a combobox if there are more then 4 IDPs configured, in this case it looks like this:
=> add a combobox instead of buttons to select the login method if more then 4 different IDPs are configured

js/admin.js
remove leading and trailing white space from settings to make it a little bit harder to break your SAML settings :wink:
=> remove leading and trailing white space from settings

css/selectUserBackEnd.css
the combobox is to small on Nextcloud 15 to fit in the text. This fixes it.
=> fix height of select box to select the IDP

lib/Controller/SettingsController.php
Remove error message when deleting IDPs from the setting
- `$content` isn't always an array, in this case the foreach will create an error message in the log. On the other hand doing a "foreach" over an empty array isn't really an issue, so I decided to simplify it as in L99
-  `$details` is not always an array, and the key `global` is not always set, so first test if it exists and then if it is true.
cc @juliushaertl
=> Fix error messages when deleting IDPs

lib/Controller/SAMLController.php
Let the admin know which parameter couldn't be matched to a uid and which parameters are provided by the IDP.
=> improve error messages in case SAML is not configured properly

appinfo/database.xml
Adding a PK for the table (prefix_)user_saml_users  on uid column (user_saml_users::uid).
Aside from enforcing consistency with a primary key it would add some performance gains as PK (and UK) constraint involve an implicit index (in most databases systems).
Also having a primary key (or a non null unique key) on each table is mandatory at least for MySQL Group Replication.
So it would be great if the table has one by default, PR is just one line in database.xml
For my NC 13.0.3 with user_saml 1.50 installation with MySQL, I actually do on the database :  
`ALTER TABLE `nextcloud`.`oc_user_saml_users`  ADD PRIMARY KEY (`uid`);`
=> Setting uid as primary key for the table user_saml_users

CHANGELOG.md, appinfo/database.xml, appinfo/info.xml, lib/Controller/SAMLController.php, lib/Settings/Admin.php, lib/UserBackend.php, tests/unit/Controller/SAMLControllerTest.php, tests/unit/Settings/AdminTest.php
This implements the mapping of home directories for new users.
Right now the mapping only happens when creating the user, as **changing** an existing user's home directory cannot be considered safe at the moment.
Closes #202 
Closes #206 
Signed-off-by: Daniel Klaffenbach <daniel.klaffenbach@hrz.tu-chemnitz.de>
=> Implement mapping of home directory when creating a user

templates/admin.php
As discussed with @schiessle 
The link was not visible by default so I adjusted the warning box to look like in the screenshots. I will open a server PR soon.
Also the second message wasn't shown at all, because the print was missing 🙈
=> Show hint for direct login URL

lib/Controller/SAMLController.php, lib/UserBackend.php
create user in the SAML back-end and update the attributes when the user was found on another back-end during login
fix https://github.com/nextcloud/user_saml/issues/268
@maghog @devi69 could you try to apply this two line fix to your installation and report back if this solves the problem? This might also fix https://github.com/nextcloud/user_saml/issues/282
=> always create user in the SAML back-end and update the attributes

3rdparty/composer.lock, 3rdparty/vendor/composer/ClassLoader.php, 3rdparty/vendor/composer/LICENSE, 3rdparty/vendor/composer/installed.json, 3rdparty/vendor/robrichards/xmlseclibs/CHANGELOG.txt, 3rdparty/vendor/robrichards/xmlseclibs/src/Utils/XPath.php, 3rdparty/vendor/robrichards/xmlseclibs/src/XMLSecEnc.php, 3rdparty/vendor/robrichards/xmlseclibs/src/XMLSecurityDSig.php, 3rdparty/vendor/robrichards/xmlseclibs/xmlseclibs.php
=> Bump xmlseclibs to 3.0.3

js/admin.js, lib/SAMLSettings.php, lib/Settings/Admin.php, templates/admin.php, tests/unit/Settings/AdminTest.php
Start to make the NameIDFormat configureable (mostly research on how to).
List of possible formats at https://github.com/nextcloud/user_saml/blob/master/3rdparty/vendor/onelogin/php-saml/src/Saml2/Constants.php#L29-L37
Default is unspecified: https://github.com/nextcloud/user_saml/blob/master/3rdparty/vendor/onelogin/php-saml/src/Saml2/Constants.php#L32
Todo:
=> Make NameIDFormat configurable

lib/Controller/SAMLController.php
cf #161 
With those websites configured to use SSO:
* `IDP`: the IDP / SSO service
* `N`: nextcloud instance
* `O` : an other website using the SSO
When user disconnect from site `O`, it send a request to `IDP`. `IDP` send a request to `N` (and all other websites where current user as a session opened) to disconnect the user on those websites too.
This PR fix this behaviour which was not working because of CRSF check which can not be valid in this scenario: validation must be done via the validation of the IDP SAML request.
=> fix IDP-initiated Logout

appinfo/routes.php, lib/Controller/SAMLController.php, tests/unit/AppInfo/RoutesTest.php
Some IdPs send their SLO logout requests via POST. To handle
them we need to add an entry in the routing table.
Further, we need to hack around the issue, that php-saml only
handles GET by copying the request from $_POST to $_GET.
fix #82
Signed-off-by: Frieder Schrempf <frieder.schrempf@online.de>
=> Handle SLO logout requests from IdP via POST

appinfo/app.php
Otherwise the app is being disabled in case a temporary expection like a LockWaitTimeoutException when querying the services.
=> Catch exceptions happening during service setup

appinfo/app.php
In dekstop >2.5 the login flow is used. No need to trigger the desktop saml stuff (as it won't work).
=> If the login flow is used (by default) we should not redirect desktopclients

js/admin.js, lib/SAMLSettings.php, lib/Settings/Admin.php, templates/admin.php, tests/unit/Settings/AdminTest.php
Add a separate setting for selecting a different signature algorithm.
@rullzer Sorry to disappoint you a bit with no vue rewrite yet, but I've put it on my list of things for some fun hacking :wink: 
Fixes #310 
The list of possible values is defined in [php-saml](https://github.com/onelogin/php-saml):
http://www.w3.org/2000/09/xmldsig#rsa-sha1
http://www.w3.org/2000/09/xmldsig#dsa-sha1
http://www.w3.org/2001/04/xmldsig-more#rsa-sha256
http://www.w3.org/2001/04/xmldsig-more#rsa-sha384
http://www.w3.org/2001/04/xmldsig-more#rsa-sha512
=> Add setting to specify a different signature algorithm

lib/Controller/SAMLController.php, tests/unit/Controller/SAMLControllerTest.php
Requires https://github.com/nextcloud/server/pull/21479 to fully work.
Basically don't save this info in the session (which is lax by default
starting with NC19 but also soon with new chromes and firefox). We now
save it is a cookie that is set to None. This is the best we can do I
think.
fixes #433
=> Make work with posts and cookies again

appinfo/info.xml, lib/Command/GetMetadata.php, tests/unit/Command/GetMetadataTest.php
I would like to automatically deploy a Nextcloud server and integrate it with my SSO. By the time my deployment pipeline runs the SSO configuration, the Nextcloud server is not publically reachable over HTTP yet. 
I developed this occ command to extract the SAML metadata from Nextcloud directly from the CLI, without having to start any webservers. In order to output the correct URLs it needs `overwrite.cli.url` to be set, and in my case, I also needed `htaccess.IgnoreFrontController` to avoid "index.php" showing up in endpoint URLS.
I think this might help somebody else someday, so please consider it for inclusion!
=> Add occ command to dump metadata for a given provider

lib/Controller/SAMLController.php
If the SLO throws an error we should catch it. This is so that we do not
show an error page. We should also still logout the current session.
=> Handle failing SLO

appinfo/info.xml, lib/Controller/SAMLController.php
Because of the strict samesite cookies SAML fails with the login flow.
Because the post that comes back is not transfering the proper cookies
to use the same session. Hence the token in use gets lost etc.
Now we store this all (encrypted) in a cookie. So that when we come back
we can restore the proper session.
FAQ:
* Is it elegant?
Nope!
* Does it work?
Yes!
=> Fix login flow with SAML

lib/AppInfo/Application.php, lib/Middleware/OnlyLoggedInMiddleware.php, tests/unit/Middleware/OnlyLoggedInMiddlewareTest.php
one way to easily reproduce it:
* log into Nextcloud via SAML
* in the same browser, open again https://my.nxtcld.srv/index.php/apps/user_saml/saml/selectUserBackEnd?redirectUrl=
Before the patch, you'll see a blank page with  the error.
With it, you are being redirected to the homepage of your Nextcloud instance.
=> redirects to homepage instead showing error on blank page

js/admin.js, lib/Controller/SAMLController.php
quick fix candidate for a regression introduced in https://github.com/nextcloud/user_saml/pull/430
To figure out the correct settings to fetch during session lifetime, `SAMLSettings::getPrefix` relies on the presence of the session stored value that got lost here.
=> fix missing user_saml.Idp session value which SAMLSettings rely on

lib/UserBackend.php
- is more tolerate when decoding, uuid structure is still tested later
- ensures the uid is resolved on getCurrentId()
=> fixes provisioning of userids from  encoded (objectguid) values

lib/Controller/SAMLController.php
'name' key was put in flowData table, but 'token' key was retrieved from this table, thus triggering the following error:
Undefined index: token at /nextcloud/apps/user_saml/lib/Controller/SAMLController.php#306
Signed-off-by: orandev <63342732+orandev@users.noreply.github.com>
=> Fix incorrect key name in "Login flow fix"

css/selectUserBackEnd.css
Otherwise the big gray buttons look odd on very bright theming colors:
Before:
After:
=> Always use primary color for buttons

lib/Controller/SAMLController.php
Some people seem to want to have a custom direct login text. This allows
them to set it. For now only via occ. But maybe some day we also add a
GUI component to it.
=> Allow customer directlogin text

.drone.yml, lib/UserBackend.php, tests/unit/UserBackendTest.php
There are some collisions possible. The received string is now tested against allowed characters as put down in https://tools.ietf.org/html/rfc4648#section-4
* fixes #504
=> make testEncodedObjectGUID more robust against false positives

lib/UserBackend.php, tests/unit/UserBackendTest.php
=> [stable-3.2] make testEncodedObjectGUID more robust against false positives

lib/Controller/SAMLController.php, lib/SAMLSettings.php, lib/Settings/Admin.php, tests/unit/Settings/AdminTest.php
Some SAML servers require this type of decoding, otherwise the SLO request fails. Ideally the library would perform both verifications (https://github.com/onelogin/php-saml/issues/466), but it seems upstream doesn't want to perform this change.
Until we have considered a better solution for this, this adds a new checkbox that one can configure.
Ref https://github.com/nextcloud/user_saml/issues/403
=> Allow setting of "retrieveParametersFromServer"

lib/Controller/SAMLController.php, lib/SAMLSettings.php, lib/Settings/Admin.php, tests/unit/Settings/AdminTest.php
=> [stable-3.3] slo web server decode (Backport #525)

lib/UserBackend.php
The default getter might return the primary email, here we need the system mail only.
=> use system email address getter if available

appinfo/app.php, lib/UserBackend.php, tests/unit/UserBackendTest.php
=> change displayName with IEventDispatcher + fixed tests

lib/Settings/Admin.php, templates/admin.php, tests/unit/Settings/AdminTest.php
Partly fix problems lined out in #573 
Templated wanted the values in config array, config array is only idp settings from user_saml, not the global ones.
Hope this approach is ok.
=> Fix displaying of global checkboxes in user_saml settings

js/admin.js
- when a setting is changed() fetching the meta data is run first,
before storing the value
- it may appear that a breaking change is good, or
- vice versa that a, actual fixing change does not have effect
=> fixes testing meta data before applying settings

appinfo/app.php
- in env mode, only one provider is supported
- choosing any provider would trigger env mode mechanis anyway
The scenario is this: 
1. in SAML settings select "Use build-in SAML authentication" 
2. Configure two or more valid SAML providers
3. In SAML config click "Reset settings" (id does not delete providers, only resets the mode)
4. Now In SAML settings select "Use environment variable" mode, and confiure it
5. In a private window try to log in
Expected is to be logged in automatically. Instead, the provider chooser is presented, but clicking any has no effect as environmental mode is enforced.
This is absolutely a corner case, yet it might save you hours debugging… the same behaviour is present in v4.1.1.
=> No SAML config chooser on env mode

appinfo/routes.php, lib/Controller/SAMLController.php
fixes #630 
The 'defaults' option in the route configuration is targetted at URL parameters only, but not GET parameters. The [dev docs](https://docs.nextcloud.com/server/latest/developer_manual/basics/routing.html) state:
> defaults (Optional): If this setting is given, a default value will be assumed for each URL parameter which is not present. The default values are passed in as a key => value par array
Therefore the defaults need to be written into the Controller method's signature.
=> fix signining in with IdPs other than 1

js/admin.js
When IdP id is 1, the resulting URL is `https://example.org/index.php/apps/user_saml/saml/metadata?idp=` thus setting idp to effectively 0 by presence of the GET parameter, instead of defaulting to 1. Also we only need to provide the id without any other characters, simplifying this a bit.
=> fix fetching meta data with IdP id 1

.drone.yml, .github/workflows/phpunit.yml
=> Adjust testing matrix for Nextcloud 26 on master

lib/Controller/SAMLController.php, tests/unit/Controller/SAMLControllerTest.php
When a provisioned account is required, it relies on another backend. Thus, allowing to auth depends on the presence of the user, and the enabled-state of the user.
Hence the configuration controls in the web UI are only shown when auto-provisioning is enabled. This change only implements a check and test cases in the business logic.
Follow up to #670
=> user filtering only applicable with autoprov

lib/Controller/SAMLController.php
Hotfix to fix https://github.com/nextcloud/server/issues/35708 but makes sense anyways to have consistent session locking for the full logout method.
https://github.com/nextcloud/server/pull/35723 could be considered hardening for the server method so this PR allows fixing the issue separtely without requiring the server PR.
=> Use session locking to be compatible with Nextcloud 25 during logout

appinfo/app.php
Given: the only available SAML configuration has an ID > 1 and we have a redirect scenario, the the SAML backend was hard requiring the config with IdP 1. This fixed with this PR by using the first (and only) available identifier.
=> fix(login): do not hardcode IdP to 1 on redirect

lib/UserBackend.php
Otherwise instanceof checks like https://github.com/nextcloud/server/pull/38298/files#diff-2e1b245993621bf5efdce546bacce8f0e43efb7bc5d0c8d1b8a55f17231c4158R79 would fail
=> fix: Implement IGetDisplayNameBackend

js/admin.js
There is no need to test metadata in this case.
=> fix: Do not try to validate metadata for environment variable config

lib/UserBackend.php
in NC 25 to 27 Symfony\Component\EventDispatcher\GenericEvent is expected with the old style ::firstLogin event
fixes #777
=> [stable-5.2] fix(firstLogin): use compatible GenericEvent

lib/Controller/SAMLController.php, tests/unit/Controller/SAMLControllerTest.php
consolidates reading the argument on one place.
=> refactor(Controller): read parameter only once

.github/workflows/integration.yml, .github/workflows/phpunit-oci.yml, CHANGELOG.md, appinfo/app.php, appinfo/info.xml, composer.json, composer.lock, lib/Exceptions/GroupNotFoundException.php, lib/Exceptions/NonMigratableGroupException.php, lib/GroupBackend.php, lib/GroupManager.php, lib/Jobs/MigrateGroups.php, lib/Migration/RememberLocalGroupsForPotentialMigrations.php, lib/Migration/Version6000Date20220912152700.php, lib/SAMLSettings.php, lib/Settings/Admin.php, lib/UserBackend.php, tests/integration/features/Shibboleth.feature, tests/integration/features/bootstrap/FeatureContext.php, tests/psalm-baseline.xml, tests/stub.phpstub, tests/unit/GroupBackendTest.php, tests/unit/GroupManagerTest.php, tests/unit/Settings/AdminTest.php, tests/unit/UserBackendTest.php
Work PR of #545, in good old tradition…  For it is not possible to push into #545 it's easier to have the feature branch here.
In one of the predecessor PRs group display names were a topic, with the conclusion
> makeing use of group display names so present it more user friendly, perhaps with (SAML) in brackets.
The `(SAML)` suffix is in the code currently. While stated by the younger me, it does not make me very happy:
- typical for LTR languages only
- technical term exposed to potentially unwitting end users (why should they know about this detail
- We have a FIXME that is rather wondering about adding another config flag here…
I am going to revert this, to use the value as provided from SAML again. Besides avoiding the downsides mentioned above, the end user does not have to face a …
=> Implementation of Groupbackend II

lib/GroupManager.php, tests/integration/features/Shibboleth.feature, tests/unit/GroupManagerTest.php
=> Fix: keep local groups when there is no group mapping set up

lib/Migration/Version3001Date20200630193443.php, lib/Migration/Version6001Date20240202183823.php, lib/UserBackend.php
- both table and logic where introduced with 84c1547c853081bf101528ecc60529e023ebc2ff
- … and were incompletely removed again in 9b97c7350bda2f12869b1301beffbf172570273b
Will have affect with a version bump only - will happen on release.
The `checkPassword` method was also not in use, because the `ICheckPasswordBackend` is not implemented :shrug:
=> fix(db): remove dead code and unused table

css/admin.css, templates/admin.php
Fixes the issue, reported also in #47, that means of input element fields where not clear once filled out, since only placeholders were used. I added labels now, and where applicable put example values as placeholders instead.
| Before | After |
|---|---|
| ![user_saml_before](https://github.com/nextcloud/user_saml/assets/2184312/202f1c5b-dd28-46ee-a318-307348405310) | ![user_saml_after](https://github.com/nextcloud/user_saml/assets/2184312/478f9e5b-8aa9-45c1-9293-c20413e9ac53) |
=> fix(UI): permanent labels for input elements

lib/AppInfo/Application.php, tests/stub.phpstub
fixes #811 
- the Application class is loaded before replacing the files
- therefore old code is execute, incompatible with 28, which has to be loaded in the constructor as we cannot move to IBootstrap yet
- deprecated components are replaced so that an upgrade will not break again on 28
=> [stable-5.2] fix(upgrade): exception when upgrading from 27 to 28

.github/workflows/integration.yml
- NC 30 does not support PHP 8.0 anymore
- add databases and stable branches to matrix
- adds a summary job
=> test(ci): update integration test to server reqs

lib/UserBackend.php
1. If you check for existence, then fetch a prop -> fetch the prop directly
2. If you check for existence, then delete -> delete directly
I have not tested these changes.
=> perf(db): Avoid double querying

lib/GroupBackend.php, tests/unit/GroupBackendTest.php
=> fix(Groups): take other DB errors into consideration

.github/dependabot.yml
Reverts nextcloud/user_saml#751
cf. https://github.com/nextcloud/user_saml/pull/751#issuecomment-1638721012 
now CI turns also red, cf. https://github.com/nextcloud/user_saml/pull/841
=> Revert "build(dependabot): commit vendor files in 3rdparty"

appinfo/info.xml, lib/Command/ConfigDelete.php, lib/Command/GroupMigrationCopyIncomplete.php, lib/GroupManager.php, lib/Jobs/MigrateGroups.php, lib/Migration/RememberLocalGroupsForPotentialMigrations.php, lib/Migration/TransferGroupMembers.php, lib/Service/GroupMigration.php, tests/integration/features/Shibboleth.feature, tests/integration/features/bootstrap/FeatureContext.php, tests/stub.phpstub
fixes #862 
Also contains a drive-by fix. I noticed that the list of groups is set newly on every repair step run. Commit 541cfdd6e0d1dcca1477105525a2a8da98376013 fixes this.
<details>
<summary>failing test proof</summary>
</details
=> fix(Groups): take over members during migration

CHANGELOG.md
version is already adjusted in info.xml
=> build(Release): 6.2.0

lib/UserBackend.php
This is not a before event, so the user should already have been changed
when it fires. Should fix issues with dav address book and newly mapped
saml users.
=> fix: Fire UserChangedEvent only after change happenned

lib/GroupManager.php, lib/Jobs/MigrateGroups.php, tests/integration/features/Shibboleth.feature, tests/integration/features/bootstrap/FeatureContext.php
this avoids testing one group all over again and again, which might be costly when large groups have to be tested (user facing request!).
=> fix(Groups): drop groups with mixed users from transition list

lib/Command/ConfigCreate.php
- Otherwise breaks with https://github.com/nextcloud/3rdparty/pull/1956
- So should be backported to stable30
=> fix(command): Ensure that writeln() argument is string

lib/UserBackend.php, tests/unit/UserBackendTest.php
This should help localize slowness of the attribute update process.
=> fix: Log attribute updates

lib/Controller/SAMLController.php
… so that calling it does not break when doing it manually and the redirect parameter is lost.
The empty string is also the fallback if it the redirect target was not specified in normal operations.
=> fix(Controller): make redirectUrl optional

lib/Controller/SAMLController.php, lib/Controller/SettingsController.php, lib/SAMLSettings.php, templates/admin.php
I did a bunch more testing and in #901 it seems I got the name of the config key wrong in some places.
This patch fixes the issue.
=> fix(settings): Fix settings name

lib/GroupBackend.php
SAML's GroupBackend does not allow you to set the display name of the groups.
The Nextcloud interface, ISetDisplayNameBackend, is implemented, which will enable setting the group name to work with SAML.
Also, group searching (on GroupBackend, getGroups method) also searches in display names.
=> feat(groups): add setting display name to group backend

composer.json, composer.lock
Until a new release of php-saml is issued.
Fixes failing PHPUnit test against PHP 8.4, .e.g. as in https://github.com/nextcloud/user_saml/pull/907
=> deps(php-saml): apply PHP 8.4 compat patch

lib/Command/ConfigCreate.php, lib/Command/ConfigDelete.php, lib/Command/ConfigGet.php, lib/Command/ConfigSet.php, lib/Command/GetMetadata.php, lib/Controller/SettingsController.php, lib/Controller/TimezoneController.php, lib/DavPlugin.php, lib/GroupManager.php, lib/Jobs/MigrateGroups.php, lib/Middleware/OnlyLoggedInMiddleware.php, lib/Migration/RememberLocalGroupsForPotentialMigrations.php, lib/SAMLSettings.php, lib/Settings/Admin.php, lib/Settings/Section.php, lib/UserBackend.php, lib/UserData.php
No changes, only code updates.
=> refactor: Apply code best practices PHP8+

js/admin.js
chaining .success() and .fail() was not working anymore, and jQuery is to be deprecated anyway. A step thereto! Also clears metadata step after an unsuccessful save to not be misleading.
Fixes
```
TypeError: $.ajax(...).fail(...).success is not a function
Uncaught TypeError: $.ajax(...).fail(...).success is not a function
testMetaData https://cloud.example.com/apps/user_saml/js/admin.js?v=4456f07a-2:139
success https://cloud.example.com/apps/user_saml/js/admin.js?v=4456f07a-2:155
onload https://cloud.example.com/apps/user_saml/js/admin.js?v=4456f07a-2:96
updateProvider https://cloud.example.com/apps/user_saml/js/admin.js?v=4456f07a-2:94
setSamlConfigValue https://cloud.example.com/apps/user_saml/js/admin.js?v=4456f07a-2:166
ve https://cloud.example.com/dist/core-main.js?v=4456f07a-2:1
i …
```
=> fix(UI): fix usage of $.ajax by going VanillaJS

appinfo/app.php, tests/integration/features/EnvironmentVariable.feature, tests/integration/features/bootstrap/FeatureContext.php
#549 might be fixed by this, although I am not sure if the problem can happen too when using SAML 2.0 or only when authenticating via environment variable (this pull request only fixes it when authenticating via environment variable).
[`handleApacheAuth()` can throw a `LoginException` when trying to authenticate as a disabled user](https://github.com/nextcloud/server/blob/12d39e818d25a4faa632cfd5945f7ef6ec8e8d27/lib/private/legacy/OC_User.php#L158-L161) (and it has done it [since Nextcloud 23.0.0, 22.2.1, 21.0.6 and 20.0.14](https://github.com/nextcloud/server/pull/28939)). This needs to be explicitly handled to redirect to an error page, as otherwise the login page will try to be loaded which, in turn, will try to authenticate again and cause an endless loop.
- Setup authentication via …
=> Handle LoginException when authenticating with Apache

.github/workflows/integration.yml
We had to run integration tests on github runners, as executing on the local ones was unstable some time ago. I understand issues where resolved with local runners, so we can re-enable them again.
=> ci: switch to any github runner again

CHANGELOG.md, appinfo/info.xml
It is quick after 6.4.0, but it is another fix that got ready just afterwards I released yesterday and we would like to have this shipped until tomorrow. There is no regression in 6.4.0 or anything like this.
=> build(release): 6.4.1

lib/Settings/Admin.php, tests/unit/Settings/AdminTest.php
Fixes the problem, that the option always appeard as disabled on a page reload:
[Screencast_20241205_230835.webm](https://github.com/user-attachments/assets/b4edf03c-f60d-430c-a603-4e8c45e599b7)
=> fix(UI): set value to the require_provisioned_account option also in env mode

lib/GroupManager.php, tests/unit/GroupManagerTest.php
* Add config flag to keep empty groups
Ref: #833
=> feat(keepEmptyGroups): Add app configuration parameter to keep empty groups

lib/SAMLSettings.php, lib/Settings/Admin.php, templates/admin.php, tests/unit/Settings/AdminTest.php
Right now the service provider entityId is always generated based on the nextcloud instance URL. At least Keycloak relies on that entityId to resolve the corresponding SAML2 client. This PR introduces a new optional config option to allow the admin to set a different service provider entityId manually. If no manual configuration is done, the current behavior remains as the default.
=> feat(settings): optional config option for sp entityId

lib/AppInfo/Application.php
This is not supported with environment-mode and thus should not show up. In env mode, only one configuration is possible.
=> fix: do not show login options on env mode (there is just one)

lib/SAMLSettings.php
This may happen with left over settings when switching from built-in SAML mode to env-mode, for example.
(Or with some development left overs/temporary unknown keys when switching branches)
=> fix(Settings): do not fail badly on unknown keys

REUSE.toml, lib/Migration/Version5000Date20211025124248.php, psalm.xml, tests/stubs/doctrine_dbal_schema_abstractasset.php, tests/stubs/doctrine_dbal_schema_column.php, tests/stubs/doctrine_dbal_schema_schema.php, tests/stubs/doctrine_dbal_schema_table.php
And make sures psalm works correctly in the Migration files by providing stubds for the DBAL Schema classes.
=> chore(migration): Port away from deprecated IQueryBuilder::execute
